name: Test

on:
  push:
  pull_request:
    types:
      - opened

env:
  BUILD_TYPE: Debug

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Get project name
        run: |
          echo "PROJECT_NAME=$(echo "${{ github.repository }}" | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Configure
        run: |
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          cmake --build build --target ${{ env.PROJECT_NAME }}-tests

      - name: Test
        run: cd ./build/$sub_project && ./$bin
        env:
          sub_project: tests
          bin: ${{ env.PROJECT_NAME }}-tests

      - name: Create coverage reports
        if: github.event_name == 'push'
        run: |
          pip install gcovr
          gcovr --xml coverage_report.xml --exclude '.*tests.*' --exclude '.*build.*'
          gcovr --exclude '.*tests.*' --exclude '.*build.*'
          rm -rf ./build/tests

      - name: Upload coverage reports to Codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}