name: Test

on:
  push:
  pull_request:
    types:
      - opened

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cargo build --verbose

      - name: Test
        run: cargo test --verbose